### ISSUE TITLE
Submit to CDNs

### ISSUE THREAD

**Issue by dandv** [Zolmeister/promiz#10]
* [JsDelivr](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md)
* [CDNJS](https://github.com/cdnjs/cdnjs/issues/4918)

**Comment by PeterDaveHello** [comment]
v1.0.4 in package.json, but no tag/release for v1.0.4, and promiz.min.js, promiz.mithril.js, promiz.mithril.min.js didn't update, promiz.mithril.min.js even stays v1.0.0, you should fix this first.

**Comment by Zolmeister** [comment]
fixed builds

**Comment by staxmanade** [comment]
I found this library up on https://cdnjs.com/

**Comment by PeterDaveHello** [comment]
Yeah, see https://github.com/cdnjs/cdnjs/commit/e3076f1

**Comment by Zolmeister** [comment]
Thanks

**Comment by PeterDaveHello** [comment]
no problem
