### ISSUE TITLE
global variable is undefined when file is processed as a module

### ISSUE THREAD

**Issue by pepa-linha** [Zolmeister/promiz#15]
Hello,

https://github.com/Zolmeister/promiz/blob/master/promiz.js#L2

Shouldn't it be `global = typeof window !== 'undefined' ? window : this`?

I got error `global` is undefined because file which contains promiz code is processed like a ES6 module (`<script type="module">`) where `this` is `undefined`.

**Comment by Zolmeister** [comment]
All browsers which support `<script type="module">` also support native `Promise`.

**Comment by pepa-linha** [comment]
You are right but it does not matter. I use other package which use promiz and for older browsers is bundled JS loaded in script without module and in modern browsers in module. And then an error occurs.

I can't change the third library code. I probably shouldn't load promiz when it's not needed, but I would need two bundles of the third library and it seems to me a very complicated solution if it would be enough to fix one line.

**Comment by Zolmeister** [comment]
Done
