### ISSUE TITLE
Add semicolons to the code?

### ISSUE THREAD

**Issue by dandv** [Zolmeister/promiz#8]
Thanks for writing Promiz. I found the code beautiful and a great resourced for teaching certain aspects of advanced JavaScript.

The lack of semicolons though [detracts from its value](http://benalman.com/news/2013/01/advice-javascript-semicolon-haters/). Any chance to add them?

**Comment by Zolmeister** [comment]
tl;dr ASI is a _feature_ of the language, and I find code to be _more_ readable without semicolons.

**Comment by dandv** [comment]
Will any amount of showcases where the lack of semicolons bites back, hard, convince you?

**Comment by Zolmeister** [comment]
No. I find most examples are contrived, and stem from a lack of information about how ASI works. The increase in readability that comes from not writing semicolons is far too valuable.

**Comment by weakish** [comment]
@dandv Just be careful when a line begins with `[(/+-` -- and `/+-` rarely appear in the beginning of line, so mostly just `[(` -- to avoid "Lack of semicolons bites back".

**Comment by dandv** [comment]
@weakish, also `{`:

```js
function foo() {
    var bar = 5

    return
    {
        bar: bar
    }  // surprise
}
```
