### ISSUE TITLE
How is 402 bytes calculated?

### ISSUE THREAD

**Issue by weakish** [Zolmeister/promiz#9]
> Promiz - 402 bytes (min + gzip) - as reported by uglify.js

But it reports 887 B on my machine.

```sh
; grunt uglify --verbose
...
Running tasks: uglify 
...
File promiz.min.js created: 5.75 kB → 2.35 kB → 887 B
...
```

(`grunt-cli v0.1.13, grunt v0.4.5, grunt-contrib-uglify 0.9.1, iojs 2.0.0`)

I tried it manually:

```sh
; uglifyjs promiz.js  --screw-ie8 -m --mangle-props -c -o test-size.js
; gzip -c -9 test-size.js | wc --bytes
838
```

With mangling and max compression ratio of gzip, it is still 838 B.

So how is 402 bytes calculated? Can you provide the configuration option for uglify and gzip?

Does 402 B comes from reporting error on gzip size from an old version of grunt-contrib-uglify?    gruntjs/grunt-contrib-uglify#219

**Comment by Zolmeister** [comment]
Thanks
